# Generated by Django 4.1.5 on 2023-01-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full name')),
                ('username', models.CharField(max_length=100, verbose_name='Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
